In [59]:
import pandas as pd
import numpy as np

In [60]:
df = pd.read_csv('dataset.csv')
df

,Name,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Result
0,Name_1,37.454012,95.071431,73.199394,59.865848,15.601864,15.599452,Yes
1,Name_2,5.808361,86.617615,60.111501,70.807258,2.058449,96.990985,No
2,Name_3,83.244264,21.233911,18.182497,18.340451,30.424224,52.475643,No
3,Name_4,43.194502,29.122914,61.185289,13.949386,29.214465,36.636184,No
4,Name_5,45.606998,78.517596,19.967378,51.423444,59.241457,4.645041,Yes
5,Name_6,60.754485,17.052412,6.505159,94.888554,96.563203,80.839735,Yes
6,Name_7,30.461377,9.767211,68.423303,44.015249,12.203823,49.517691,Yes
7,Name_8,3.438852,90.932040,25.877998,66.252228,31.171108,52.006802,No
8,Name_9,54.671028,18.485446,96.958463,77.513282,93.949894,89.482735,No
9,Name_10,59.789998,92.187424,8.849250,19.598286,4.522729,32.533033,No
10,Name_11,38.867729,27.134903,82.873751,35.675333,28.093451,54.269608,Yes
11,Name_12,14.092422,80.219698,7.455064,98.688694,77.224477,19.871568,No
12,Name_13,0.552212,81.546143,70.685734,72.900717,77.127035,7.404465,No
13,Name_14,35.846573,11.586906,86.310343,62.329813,33.089802,6.355835,No
14,Name_15,31.098232,32.518332,72.960618,63.755747,88.721274,47.221493,No
15,Name_16,11.959425,71.324479,76.078505,56.127720,77.096718,49.379560,Yes
16,Name_17,52.273283,42.754102,2.541913,10.789143,3.142919,63.641041,Yes
17,Name_18,31.435598,50.857069,90.756647,24.929223,41.038292,75.555114,No
18,Name_19,22.879817,7.697991,28.975145,16.122129,92.969765,80.812038,Yes
19,Name_20,63.340376,87.146059,80.367208,18.657006,89.255900,53.934224,Yes
20,Name_21,80.744016,89.609130,31.800347,11.005192,22.793516,42.710779,No
21,Name_22,81.801477,86.073058,0.695213,51.074730,41.741100,22.210781,No
22,Name_23,11.986537,33.761517,94.290970,32.320293,51.879062,70.301896,Yes
23,Name_24,36.362960,97.178208,96.244729,25.178230,49.724851,30.087831,No
24,Name_25,28.484049,3.688695,60.956433,50.267902,5.147875,27.864646,Yes
25,Name_26,90.826589,23.956189,14.489487,48.945276,98.565045,24.205527,No
26,Name_27,67.213555,76.161962,23.763754,72.821635,36.778313,63.230583,Yes
27,Name_28,63.352971,53.577468,9.028977,83.530250,32.078006,18.651851,No
28,Name_29,4.077514,59.089294,67.756436,1.658783,51.209306,22.649578,Yes
29,Name_30,64.517279,17.436643,69.093774,38.673535,93.672999,13.752094,Yes
30,Name_31,34.106635,11.347352,92.469362,87.733935,25.794163,65.998405,Yes
31,Name_32,81.722220,55.520081,52.965058,24.185229,9.310277,89.721576,No
32,Name_33,90.041806,63.310146,33.902979,34.920957,72.595568,89.711026,Yes
33,Name_34,88.708642,77.987555,64.203165,8.413996,16.162871,89.855419,Yes
34,Name_35,60.642906,0.919705,10.147154,66.350177,0.506158,16.080805,No
35,Name_36,54.873379,69.189520,65.196126,22.426931,71.217922,23.724909,No
36,Name_37,32.539970,74.649141,64.963290,84.922341,65.761289,56.830860,Yes
37,Name_38,9.367477,36.771580,26.520237,24.398964,97.301055,39.309772,Yes
38,Name_39,89.204656,63.113863,79.481130,50.263709,57.690388,49.251769,No
39,Name_40,19.524299,72.245212,28.077236,2.431597,64.547230,17.711068,No
40,Name_41,94.045858,95.392858,91.486439,37.015870,1.545662,92.831856,No
41,Name_42,42.818415,96.665482,96.361998,85.300946,29.444889,38.509773,No
42,Name_43,85.113667,31.692201,16.949275,55.680126,93.615477,69.602980,No
43,Name_44,57.006117,9.717649,61.500723,99.005385,14.008402,51.832965,Yes
44,Name_45,87.737307,74.076862,69.701574,70.248408,35.949115,29.359184,No
45,Name_46,80.936116,81.011339,86.707232,91.324055,51.134240,50.151629,Yes
46,Name_47,79.829518,64.996393,70.196688,79.579267,89.000534,33.799516,Yes
47,Name_48,37.558295,9.398194,57.828014,3.594227,46.559802,54.264463,Yes
48,Name_49,28.654125,59.083326,3.050025,3.734819,82.260056,36.019064,No
49,Name_50,12.706051,52.224326,76.999355,21.582103,62.289048,8.534746,Yes

In [61]:
df.head()

,Name,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Result
0,Name_1,37.454012,95.071431,73.199394,59.865848,15.601864,15.599452,Yes
1,Name_2,5.808361,86.617615,60.111501,70.807258,2.058449,96.990985,No
2,Name_3,83.244264,21.233911,18.182497,18.340451,30.424224,52.475643,No
3,Name_4,43.194502,29.122914,61.185289,13.949386,29.214465,36.636184,No
4,Name_5,45.606998,78.517596,19.967378,51.423444,59.241457,4.645041,Yes

In [62]:
df.shape

(50, 8)

In [63]:
df.columns

Index(['Name', 'Feature_1', 'Feature_2', 'Feature_3', 'Feature_4', 'Feature_5',
       'Feature_6', 'Result'],
      dtype='object')

In [64]:
df = df.drop(columns='Name')
df

    Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6 Result
0   37.454012  95.071431  73.199394  59.865848  15.601864  15.599452    Yes
1    5.808361  86.617615  60.111501  70.807258   2.058449  96.990985     No
2   83.244264  21.233911  18.182497  18.340451  30.424224  52.475643     No
3   43.194502  29.122914  61.185289  13.949386  29.214465  36.636184     No
4   45.606998  78.517596  19.967378  51.423444  59.241457   4.645041    Yes
5   60.754485  17.052412   6.505159  94.888554  96.563203  80.839735    Yes
6   30.461377   9.767211  68.423303  44.015249  12.203823  49.517691    Yes
7    3.438852  90.932040  25.877998  66.252228  31.171108  52.006802     No
8   54.671028  18.485446  96.958463  77.513282  93.949894  89.482735     No
9   59.789998  92.187424   8.849250  19.598286   4.522729  32.533033     No
10  38.867729  27.134903  82.873751  35.675333  28.093451  54.269608    Yes
11  14.092422  80.219698   7.455064  98.688694  77.224477  19.871568     No
12   0.552212  81.546143  70.685734  72.900717  77.127035   7.404465     No
13  35.846573  11.586906  86.310343  62.329813  33.089802   6.355835     No
14  31.098232  32.518332  72.960618  63.755747  88.721274  47.221493     No
15  11.959425  71.324479  76.078505  56.127720  77.096718  49.379560    Yes
16  52.273283  42.754102   2.541913  10.789143   3.142919  63.641041    Yes
17  31.435598  50.857069  90.756647  24.929223  41.038292  75.555114     No
18  22.879817   7.697991  28.975145  16.122129  92.969765  80.812038    Yes
19  63.340376  87.146059  80.367208  18.657006  89.255900  53.934224    Yes
20  80.744016  89.609130  31.800347  11.005192  22.793516  42.710779     No
21  81.801477  86.073058   0.695213  51.074730  41.741100  22.210781     No
22  11.986537  33.761517  94.290970  32.320293  51.879062  70.301896    Yes
23  36.362960  97.178208  96.244729  25.178230  49.724851  30.087831     No
24  28.484049   3.688695  60.956433  50.267902   5.147875  27.864646    Yes
25  90.826589  23.956189  14.489487  48.945276  98.565045  24.205527     No
26  67.213555  76.161962  23.763754  72.821635  36.778313  63.230583    Yes
27  63.352971  53.577468   9.028977  83.530250  32.078006  18.651851     No
28   4.077514  59.089294  67.756436   1.658783  51.209306  22.649578    Yes
29  64.517279  17.436643  69.093774  38.673535  93.672999  13.752094    Yes
30  34.106635  11.347352  92.469362  87.733935  25.794163  65.998405    Yes
31  81.722220  55.520081  52.965058  24.185229   9.310277  89.721576     No
32  90.041806  63.310146  33.902979  34.920957  72.595568  89.711026    Yes
33  88.708642  77.987555  64.203165   8.413996  16.162871  89.855419    Yes
34  60.642906   0.919705  10.147154  66.350177   0.506158  16.080805     No
35  54.873379  69.189520  65.196126  22.426931  71.217922  23.724909     No
36  32.539970  74.649141  64.963290  84.922341  65.761289  56.830860    Yes
37   9.367477  36.771580  26.520237  24.398964  97.301055  39.309772    Yes
38  89.204656  63.113863  79.481130  50.263709  57.690388  49.251769     No
39  19.524299  72.245212  28.077236   2.431597  64.547230  17.711068     No
40  94.045858  95.392858  91.486439  37.015870   1.545662  92.831856     No
41  42.818415  96.665482  96.361998  85.300946  29.444889  38.509773     No
42  85.113667  31.692201  16.949275  55.680126  93.615477  69.602980     No
43  57.006117   9.717649  61.500723  99.005385  14.008402  51.832965    Yes
44  87.737307  74.076862  69.701574  70.248408  35.949115  29.359184     No
45  80.936116  81.011339  86.707232  91.324055  51.134240  50.151629    Yes
46  79.829518  64.996393  70.196688  79.579267  89.000534  33.799516    Yes
47  37.558295   9.398194  57.828014   3.594227  46.559802  54.264463    Yes
48  28.654125  59.083326   3.050025   3.734819  82.260056  36.019064     No
49  12.706051  52.224326  76.999355  21.582103  62.289048   8.534746    Yes

In [65]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['Result'])
y = df['Result']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X

    Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0   37.454012  95.071431  73.199394  59.865848  15.601864  15.599452
1    5.808361  86.617615  60.111501  70.807258   2.058449  96.990985
2   83.244264  21.233911  18.182497  18.340451  30.424224  52.475643
3   43.194502  29.122914  61.185289  13.949386  29.214465  36.636184
4   45.606998  78.517596  19.967378  51.423444  59.241457   4.645041
5   60.754485  17.052412   6.505159  94.888554  96.563203  80.839735
6   30.461377   9.767211  68.423303  44.015249  12.203823  49.517691
7    3.438852  90.932040  25.877998  66.252228  31.171108  52.006802
8   54.671028  18.485446  96.958463  77.513282  93.949894  89.482735
9   59.789998  92.187424   8.849250  19.598286   4.522729  32.533033
10  38.867729  27.134903  82.873751  35.675333  28.093451  54.269608
11  14.092422  80.219698   7.455064  98.688694  77.224477  19.871568
12   0.552212  81.546143  70.685734  72.900717  77.127035   7.404465
13  35.846573  11.586906  86.310343  62.329813  33.089802   6.355835
14  31.098232  32.518332  72.960618  63.755747  88.721274  47.221493
15  11.959425  71.324479  76.078505  56.127720  77.096718  49.379560
16  52.273283  42.754102   2.541913  10.789143   3.142919  63.641041
17  31.435598  50.857069  90.756647  24.929223  41.038292  75.555114
18  22.879817   7.697991  28.975145  16.122129  92.969765  80.812038
19  63.340376  87.146059  80.367208  18.657006  89.255900  53.934224
20  80.744016  89.609130  31.800347  11.005192  22.793516  42.710779
21  81.801477  86.073058   0.695213  51.074730  41.741100  22.210781
22  11.986537  33.761517  94.290970  32.320293  51.879062  70.301896
23  36.362960  97.178208  96.244729  25.178230  49.724851  30.087831
24  28.484049   3.688695  60.956433  50.267902   5.147875  27.864646
25  90.826589  23.956189  14.489487  48.945276  98.565045  24.205527
26  67.213555  76.161962  23.763754  72.821635  36.778313  63.230583
27  63.352971  53.577468   9.028977  83.530250  32.078006  18.651851
28   4.077514  59.089294  67.756436   1.658783  51.209306  22.649578
29  64.517279  17.436643  69.093774  38.673535  93.672999  13.752094
30  34.106635  11.347352  92.469362  87.733935  25.794163  65.998405
31  81.722220  55.520081  52.965058  24.185229   9.310277  89.721576
32  90.041806  63.310146  33.902979  34.920957  72.595568  89.711026
33  88.708642  77.987555  64.203165   8.413996  16.162871  89.855419
34  60.642906   0.919705  10.147154  66.350177   0.506158  16.080805
35  54.873379  69.189520  65.196126  22.426931  71.217922  23.724909
36  32.539970  74.649141  64.963290  84.922341  65.761289  56.830860
37   9.367477  36.771580  26.520237  24.398964  97.301055  39.309772
38  89.204656  63.113863  79.481130  50.263709  57.690388  49.251769
39  19.524299  72.245212  28.077236   2.431597  64.547230  17.711068
40  94.045858  95.392858  91.486439  37.015870   1.545662  92.831856
41  42.818415  96.665482  96.361998  85.300946  29.444889  38.509773
42  85.113667  31.692201  16.949275  55.680126  93.615477  69.602980
43  57.006117   9.717649  61.500723  99.005385  14.008402  51.832965
44  87.737307  74.076862  69.701574  70.248408  35.949115  29.359184
45  80.936116  81.011339  86.707232  91.324055  51.134240  50.151629
46  79.829518  64.996393  70.196688  79.579267  89.000534  33.799516
47  37.558295   9.398194  57.828014   3.594227  46.559802  54.264463
48  28.654125  59.083326   3.050025   3.734819  82.260056  36.019064
49  12.706051  52.224326  76.999355  21.582103  62.289048   8.534746

In [66]:
y

0     Yes
1      No
2      No
3      No
4     Yes
5     Yes
6     Yes
7      No
8      No
9      No
10    Yes
11     No
12     No
13     No
14     No
15    Yes
16    Yes
17     No
18    Yes
19    Yes
20     No
21     No
22    Yes
23     No
24    Yes
25     No
26    Yes
27     No
28    Yes
29    Yes
30    Yes
31     No
32    Yes
33    Yes
34     No
35     No
36    Yes
37    Yes
38     No
39     No
40     No
41     No
42     No
43    Yes
44     No
45    Yes
46    Yes
47    Yes
48     No
49    Yes
Name: Result, dtype: object

In [74]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_test,y_test)

arr1 = np.array([13, 54, 67, 89, 40, 20]).reshape(1, -1)
arr2 = np.array([12, 31, 47, 10, 40, 50]).reshape(1, -1)
arr3 = np.array([28, 3, 60, 50, 5, 27]).reshape(1, -1)

predict1 = model.predict(arr1)
predict2 = model.predict(arr2)
predict3 = model.predict(arr3)

print(predict1)
print(predict2)
print(predict3)

c:\Users\vpran\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\vpran\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\vpran\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

['No']
['Yes']
['Yes']